### PR TITLE
Add Creative Commons license

### PR DESCRIPTION
**Pull request by jancborchardt**
This is important so people can actually contribute and use your work. :slightly_smiling_face: 

Please review @TheHennes36 @noahkna @rbnxbk @GitStudentNen

### CODE REVIEW

**Comment by TheHennes36** [comment]
How do you add the license? Do you embed the picture of the license badge or is it enough to just mention it in the text?

**Comment by jancborchardt** [comment]
Yes – merging this pull request (which states it in the readme, with image) is enough to do that. :)

**Review by TheHennes36 — APPROVED** [review]
We can merge this request

**Comment by jancborchardt** [comment]
Cool! :) @TheHennes36 @rbnxbk @noahkna @GitStudentNen did you already reach out again to Project Gutenberg?

I just tweeted at https://twitter.com/jancborchardt/status/1065241071012233218, hopefully they’ll react or someone else has a contact. :) Will also mail the people again.

**Comment by jancborchardt** [comment]
Also, it would be great if you can also post your work to the [Open Source Design forum](https://discourse.opensourcedesign.net/)! The "Visual identity" category fits perfectly, and you can simply link to the readme of the repository here and add one or more of the images. :slightly_smiling_face: 

Let’s try to make this real!

**Comment by TheHennes36** [comment]
Hey Christoph

Problem is i can’t get to log in using my GitHub Account… It always tells me that the authorization would be missing. However I got a mail from GitHub saying that Opensourcedesign just got authorized… strange.
Also I couldn’t reach out to Gutenberg.org <http://gutenberg.org/>, since Im unable to see the email address (the contact page is blocked swell because of that copyright issue)
LG Hannes

**Comment by jancborchardt** [comment]
I got an email back from them – just forwarded it to you and the others. :)

One thing we would need to change in the license is to move from Creative Commons to Public Domain, as the new Project Gutenberg will be fully public domain. Would that be ok with you?

**Comment by noahkna** [comment]
Just wrote the mail, what a coincidence :D
On my side the change of license would be no problem at all, if the others agree as well. :)

**Comment by TheHennes36** [comment]
Wow! Sounds Awesome! :)
Im definitely in!

**Comment by rbnxbk** [comment]
me too!

**Comment by jancborchardt** [comment]
@noahkna @TheHennes36 @rbnxbk cool! :) Did you read the mail I forwarded you the other day? What do you think about it otherwise?

**Comment by TheHennes36** [comment]
I think its pretty cool they like the logo. Also good that they upload the project for the redesign on GitHub. Just quite busy right now so we might not be able to do too much but Ill definitely try. Will they provide us the link once the project is online?

**Comment by jancborchardt** [comment]
Just replied to Greg and put you in cc (left out Noah E as he didn’t reply, but feel free to add him if he’s interested). :slightly_smiling_face: Hopefully the collaboration kicks off soon!

No worries about being busy – I can also put in some more time for this, and the mockup part is already very nicely done. We’ll first have to check which points everyone is at.

**Pull request merged**
